version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONTEXT=development
    volumes:
      - .:/app:rw
    command: python -c "from app import create_app; create_app().run(host='0.0.0.0', port=5000)"
